services:
  networkscan:
    build: .
    container_name: networkscan
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    environment:
      - TZ=Europe/Paris
    env_file:
      - .env
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command: [ "python", "runner.py" ]
    restart: unless-stopped
